### ISSUE TITLE
[FEATURE] - ADD RENOVATEBOT FOR GOLANG DEPENDECIES

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/machineshop#47]
- [ ] add bot 
- [ ] test

**Comment by xlai89** [comment]
initialized renovate. 
next step: enable automerge
* status check required
* strategy: ff & rebase

**Comment by xlai89** [comment]
Automerge and a schedule were enabled according to this [best practice](https://www.augmentedmind.de/2023/07/30/renovate-bot-cheat-sheet/) in PR #57 and #58.

A setting modification for `main` branch was necessary to set successful pipelines in the env "k8s" as required before merging PR, otherwise PR got automerged before finishing pipelines, like #59.

**Comment by xlai89** [comment]
Automerge works generally well. There is one issue though: 

Successful checks (github action pipelines) are prerequisites for an automerge. If the main branch got new commits during the time when a renovate PR is open, rebase will take place after checks. But **rebasing does not trigger new checks**, causing 0 checks in the renovate PR, preventing automerge.

Workaround: close the PR and reopen it. If the checks succeed, automerge will take place and dependencies get updated.

Currently [`prHourlyLimit`](https://docs.renovatebot.com/configuration-options/#prhourlylimit) is set to 1, avoiding concurrent renovate PRs during the renovate schedule.
